---
- name: docker login 
  hosts: "{{ variable_host }}"
  become: true
  vars:
    username: "{{username}}"
    password: "{{password}}" 
    registry: ghcr.io

  tasks:
    - name: Log into private registry and force re-authorization
      docker_login:
        registry: "{{ registry }}" 
        username: "{{ username }}" 
        password: "{{ password }}" 
        reauthorize: yes
