---
- name: My playbook
  hosts: "{{ variable_host | default('all') }}"
  tasks:
    - name: run one
      import_tasks: tasks/one.yaml

    - name: Leaving a mark
      command: "touch /tmp/ansible_was_here"
