---
- name: run image 
  hosts: "{{ host }}"
  become: true
  vars:
    container_count: 1 
    default_container_name: field-seating-api 
    default_container_image: "ghcr.io/field-seating/field-seating-api:{{ tag }}" 
  tasks:
    - name: init docker setup 
      import_tasks: tasks/init-docker-setup.yaml

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      community.docker.docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        recreate: yes
        exposed_ports:
          - 3000 
        ports:
          - "3000:3000" 
    - name: docker prune 
      import_tasks: tasks/docker-prune.yml
